# Generated by Django 2.2.8 on 2019-12-15 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('signin_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
