# Generated by Django 2.2.8 on 2020-01-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='group_pk',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupboard',
            old_name='group_pk',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_pk',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupnotice',
            old_name='group_pk',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupschedule',
            old_name='group_pk',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='survey_question_pk',
            new_name='survey_question',
        ),
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='survey_pk',
            new_name='survey',
        ),
    ]
