# Generated by Django 2.2.8 on 2019-12-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='name',
        ),
    ]
