# Generated by Django 2.2.8 on 2019-12-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delos', '0004_auto_20191216_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
